// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repo.Context;

#nullable disable

namespace repo.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DisciplineStudent", b =>
                {
                    b.Property<int>("DisciplinesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentRecordBookNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("DisciplinesId", "StudentRecordBookNumber");

                    b.HasIndex("StudentRecordBookNumber");

                    b.ToTable("StudentDisciplines", (string)null);
                });

            modelBuilder.Entity("repo.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("repo.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("repo.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("repo.Models.Student", b =>
                {
                    b.Property<string>("RecordBookNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("RecordBookNumber");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasDiscriminator<string>("StudentType").HasValue("Student");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("repo.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("repo.Models.FullTimeStudent", b =>
                {
                    b.HasBaseType("repo.Models.Student");

                    b.Property<double>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("EgeScore")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("FullTime");
                });

            modelBuilder.Entity("repo.Models.PartTimeStudent", b =>
                {
                    b.HasBaseType("repo.Models.Student");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PartTime");
                });

            modelBuilder.Entity("repo.Models.TargetStudent", b =>
                {
                    b.HasBaseType("repo.Models.Student");

                    b.Property<string>("TargetCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("TEXT");

                    b.ToTable("Students", t =>
                        {
                            t.Property("TuitionFee")
                                .HasColumnName("TargetStudent_TuitionFee");
                        });

                    b.HasDiscriminator().HasValue("Target");
                });

            modelBuilder.Entity("DisciplineStudent", b =>
                {
                    b.HasOne("repo.Models.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("repo.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentRecordBookNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("repo.Models.Discipline", b =>
                {
                    b.HasOne("repo.Models.Teacher", "Teacher")
                        .WithMany("Disciplines")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("repo.Models.Student", b =>
                {
                    b.HasOne("repo.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("repo.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("repo.Models.Department", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("repo.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("repo.Models.Teacher", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
